coverage_service: cobertura_xml
xcodeproj: standard-swift.xcodeproj
scheme: standard-swift
configuration: Release
source_directory: ./
output_directory: ./
ignore:
  - ExamplePodCode/*
  - ProjectTestsGroup/*