language: swift
osx_image: xcode11
before_install:
  - brew update
  - brew upgrade python
  - pip install requests
script:
  - xcodebuild -scheme standard-swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' build test
  - bash <(curl -s https://codecov.io/bash) 
  - python request.py


 