language: swift
osx_image: xcode11
before_install:
  - brew update
  - brew upgrade python
  - pip install requests
  - rvm use $RVM_RUBY_VERSION
install:
  - gem install slather
script:
  - xcodebuild -scheme standard-swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' build test
  - pwd 
  - slather 
  - bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml
  - python request.py


 