jobs:
  include:
    - stage: "Build Swift Proj"
    - language: swift
      osx_image: xcode11
      script:
        - xcodebuild -scheme standard-swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' build test
        - bash <(curl -s https://codecov.io/bash) -t 481266e2-b6e4-4309-af21-13f0a9df1064
    - stage: "Request Coverage From API"
    - language: python
      python: 3.6
      before_install:
        - pip install requests
      script:
        - python request.py
