language: swift
osx_image: xcode11
script:
  - xcodebuild -scheme standard-swift -sdk iphonesimulator -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' -enableCodeCoverage YES clean build test
  - cd Build/Build/ProfileData/
  - ls -R
  #- xcrun llvm-cov export -format="lcov" -instr-profile  > info.lcov

