language: swift
osx_image: xcode11
before_install:
  - brew update
  - brew upgrade python
  - pip install requests
script:
  - xcodebuild -scheme standard-swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' build test
  - slather
  - bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml -t 481266e2-b6e4-4309-af21-13f0a9df1064
  - python request.py
